#!/usr/bin/env bash
# Yeni VPS IP’yi arayüze ekler ve çıkış kaynağını buna çeker.
# Sağlayıcı: IP 85.95.240.184 · Netmask 255.255.255.0 · Gateway 85.95.240.1
# Kullanım (sunucuda root):
#   sudo bash deploy/add-production-ip.sh
# Ardından sağlayıcının istediği gibi power off / power on yapın.
# DNS: tamkobi.com A kaydını 85.95.240.184 yapın.
# İşNet / Enpara / Kuveyt whitelist’e 85.95.240.184 ekleyin.

set -euo pipefail

NEW_IP="${TAMKOBI_PRODUCTION_IP:-85.95.240.184}"
PREFIX="${TAMKOBI_PRODUCTION_PREFIX:-24}"
GATEWAY="${TAMKOBI_PRODUCTION_GATEWAY:-85.95.240.1}"
IFACE="${TAMKOBI_NET_IFACE:-}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "root gerekli: sudo bash $0" >&2
  exit 1
fi

if [[ -z "$IFACE" ]]; then
  IFACE="$(ip -4 route show default 2>/dev/null | awk '{print $5; exit}')"
fi
if [[ -z "$IFACE" ]]; then
  echo "Varsayılan arayüz bulunamadı. TAMKOBI_NET_IFACE=eth0 ile tekrar deneyin." >&2
  exit 1
fi

echo "Arayüz: $IFACE"
echo "Eklenen: ${NEW_IP}/${PREFIX}  gateway=${GATEWAY}"

# Alias (ikincil adres)
if ip -4 addr show dev "$IFACE" | grep -q "inet ${NEW_IP}/"; then
  echo "IP zaten tanımlı."
else
  ip addr add "${NEW_IP}/${PREFIX}" dev "$IFACE"
  echo "ip addr add tamam."
fi

# Çıkış trafiğinin kaynağı yeni IP olsun (whitelist için şart)
ip route replace default via "$GATEWAY" dev "$IFACE" src "$NEW_IP" || \
  ip route replace default via "$GATEWAY" src "$NEW_IP"

# Netplan kalıcılık (Ubuntu)
NETPLAN_DIR=/etc/netplan
if [[ -d "$NETPLAN_DIR" ]]; then
  TARGET="${NETPLAN_DIR}/99-tamkobi-production-ip.yaml"
  cat >"$TARGET" <<EOF
# Generated by deploy/add-production-ip.sh — ${NEW_IP}
network:
  version: 2
  ethernets:
    ${IFACE}:
      addresses:
        - ${NEW_IP}/${PREFIX}
      routes:
        - to: default
          via: ${GATEWAY}
          table: 100
      routing-policy:
        - from: ${NEW_IP}
          table: 100
EOF
  # Mevcut netplan DHCP/static ile çakışmasın diye yalnızca ek route politikası.
  # Tam adres listesini provider şablonuna göre elle birleştirmeniz gerekebilir.
  echo "Netplan taslağı yazıldı: $TARGET"
  echo "Mevcut netplan dosyanızda ${NEW_IP}/${PREFIX} adresini addresses altına ekleyin,"
  echo "sonra: netplan apply"
fi

echo
echo "Doğrulama:"
ip -4 addr show dev "$IFACE" | sed -n '1,20p'
echo "Çıkış IP (ipify): $(curl -4 -fsS --max-time 8 https://api.ipify.org || echo 'tespit edilemedi')"
echo
echo "Sonraki adımlar:"
echo "  1) Panelden power off / power on"
echo "  2) DNS A: tamkobi.com → ${NEW_IP}"
echo "  3) İşNet: VKN + ${NEW_IP} + InvoiceService → efaturadestek@nettefatura.com.tr"
echo "  4) Enpara / Kuveyt portal whitelist → ${NEW_IP}"
echo "  5) curl -4 https://api.ipify.org  → ${NEW_IP} görmeli"
