#!/usr/bin/env bash
# İkinci üretim IP’sini arayüze ekler; birincisini (85.95.240.136) korur.
#
#   Birincil : 85.95.240.136  (mevcut — DNS / varsayılan çıkış)
#   İkincil  : 85.95.240.184  (yeni — Netmask 255.255.255.0 · Gateway 85.95.240.1)
#
# Kullanım (sunucuda root):
#   sudo bash deploy/add-production-ip.sh
# Ardından sağlayıcı paneli: power off / power on.
# İşNet / Enpara / Kuveyt whitelist’e İKİ IP’yi de ekleyin.

set -euo pipefail

PRIMARY_IP="${TAMKOBI_PRIMARY_IP:-85.95.240.136}"
SECONDARY_IP="${TAMKOBI_SECONDARY_IP:-85.95.240.184}"
PREFIX="${TAMKOBI_PRODUCTION_PREFIX:-24}"
GATEWAY="${TAMKOBI_PRODUCTION_GATEWAY:-85.95.240.1}"
IFACE="${TAMKOBI_NET_IFACE:-}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "root gerekli: sudo bash $0" >&2
  exit 1
fi

if [[ -z "$IFACE" ]]; then
  IFACE="$(ip -4 route show default 2>/dev/null | awk '{print $5; exit}')"
fi
if [[ -z "$IFACE" ]]; then
  echo "Varsayılan arayüz bulunamadı. TAMKOBI_NET_IFACE=eth0 ile tekrar deneyin." >&2
  exit 1
fi

echo "Arayüz: $IFACE"
echo "Birincil (korunur): ${PRIMARY_IP}/${PREFIX}"
echo "İkincil (eklenir):  ${SECONDARY_IP}/${PREFIX}  gateway=${GATEWAY}"

add_addr() {
  local ip="$1"
  if ip -4 addr show dev "$IFACE" | grep -q "inet ${ip}/"; then
    echo "  ${ip} zaten tanımlı."
  else
    ip addr add "${ip}/${PREFIX}" dev "$IFACE"
    echo "  ip addr add ${ip}/${PREFIX} tamam."
  fi
}

add_addr "$PRIMARY_IP"
add_addr "$SECONDARY_IP"

# Varsayılan çıkış birincilden kalsın (mevcut whitelist / DNS bozulmasın).
# İkincilden bilinçli çıkış için: TAMKOBI_EGRESS_SRC=secondary sudo bash deploy/add-production-ip.sh
EGRESS_SRC="${TAMKOBI_EGRESS_SRC:-primary}"
if [[ "$EGRESS_SRC" == "secondary" ]]; then
  ip route replace default via "$GATEWAY" dev "$IFACE" src "$SECONDARY_IP" || \
    ip route replace default via "$GATEWAY" src "$SECONDARY_IP"
  echo "Varsayılan çıkış kaynağı: ${SECONDARY_IP}"
else
  ip route replace default via "$GATEWAY" dev "$IFACE" src "$PRIMARY_IP" 2>/dev/null || true
  echo "Varsayılan çıkış kaynağı: ${PRIMARY_IP} (ikincil yalnızca dinleme/alias)"
fi

NETPLAN_DIR=/etc/netplan
if [[ -d "$NETPLAN_DIR" ]]; then
  TARGET="${NETPLAN_DIR}/99-tamkobi-dual-ip.yaml"
  cat >"$TARGET" <<EOF
# Generated by deploy/add-production-ip.sh — dual IP
# Mevcut netplan şablonunuzla birleştirin; çakışan ethernets.${IFACE} bloğu varsa tek dosyada tutun.
network:
  version: 2
  ethernets:
    ${IFACE}:
      addresses:
        - ${PRIMARY_IP}/${PREFIX}
        - ${SECONDARY_IP}/${PREFIX}
      routes:
        - to: default
          via: ${GATEWAY}
EOF
  echo "Netplan taslağı: $TARGET"
  echo "Mevcut netplan’da addresses altına her iki IP’yi ekleyip: netplan try && netplan apply"
fi

echo
echo "Doğrulama:"
ip -4 addr show dev "$IFACE" | sed -n '1,30p'
echo "Çıkış IP (ipify): $(curl -4 -fsS --max-time 8 https://api.ipify.org || echo 'tespit edilemedi')"
echo
echo "Sonraki adımlar:"
echo "  1) Panelden power off / power on"
echo "  2) DNS: tamkobi.com A → ${PRIMARY_IP} (isterseniz ikinci A → ${SECONDARY_IP})"
echo "  3) İşNet whitelist: ${PRIMARY_IP} VE ${SECONDARY_IP} + InvoiceService"
echo "  4) Enpara / Kuveyt whitelist: ${PRIMARY_IP} VE ${SECONDARY_IP}"
echo "  5) Her iki adres: ip -4 addr show | grep -E '${PRIMARY_IP}|${SECONDARY_IP}'"
